# Buildpack API version
api = "0.7"

# Buildpack ID and metadata
[buildpack]
  id = "tomh4/python-poetry"
  version = "0.0.6"
  
# Stacks that the buildpack will work with
[[stacks]]
  id = "io.buildpacks.samples.stacks.bionic"


